### ISSUE TITLE
composer require littlesqx/aint-queue -vvv

### ISSUE THREAD

**Issue by pliu22** [Littlesqx/aint-queue#23]
Using version ^1.1 for littlesqx/aint-queue
Root package 'littlesqx/aint-queue' cannot require itself in its composer.json

**Comment by Littlesqx** [comment]
你好，谢谢反馈。如果是直接 `git clone` 后的，不用 `composer require littlesqx/aint-queue`；可以直接 `composer install`。

**Comment by wrndlb** [comment]
好的

**Comment by pliu22** [comment]
> 你好，谢谢反馈。如果是直接 `git clone` 后的，不用 `composer require littlesqx/aint-queue`；可以直接 `composer install`。

好的 我学习一下你的代码
