### ISSUE TITLE
其他框架如何跟这个结合?

### ISSUE THREAD

**Issue by jonny77** [Littlesqx/aint-queue#27]
1.使用 http  或者 RPC 方式.塞入任务,并消费队列
2.其他框架直接将任务塞入 redis.由这个东东读取之后自动消费队列
????
另外,稳定吗?可用于生产吗

**Comment by Littlesqx** [comment]
你好，谢谢反馈。接入其他框架，只需要保证任务类中的执行代码（可能引用了外部类）支持 composer 加载就可以了，如果不支持那需要手动引入需要的代码。

1. 是建议还是？
2. 是的。保证生产者和消费者都在同一个项目即可。
3. 在我司已经生产验证，每天消费百万消息。

**Comment by Littlesqx** [comment]
我不能保证后续继续维护，代码其实不多和不难，你也可以 fork 一个自己改造。一起维护

**Comment by jonny77** [comment]
> 你好，谢谢反馈。接入其他框架，只需要保证任务类中的执行代码（可能引用了外部类）支持 composer 加载就可以了，如果不支持那需要手动引入需要的代码。
> 
> 1. 是建议还是？
> 2. 是的。保证生产者和消费者都在同一个项目即可。
> 3. 在我司已经生产验证，每天消费百万消息。

其实我就想问有什么方式可以将别的框架跟你这个东东结合起来, 那么结合的方式是?
 1.使用 http 或者 RPC 方式.塞入任务,并消费队列? 
2.其他框架只负责往 redis 塞入任务,这个东东自动去消费队列?
3.其他好的建议是?

**Comment by Littlesqx** [comment]
> > 你好，谢谢反馈。接入其他框架，只需要保证任务类中的执行代码（可能引用了外部类）支持 composer 加载就可以了，如果不支持那需要手动引入需要的代码。
> > 
> > 1. 是建议还是？
> > 2. 是的。保证生产者和消费者都在同一个项目即可。
> > 3. 在我司已经生产验证，每天消费百万消息。
> 
> 其实我就想问有什么方式可以将别的框架跟你这个东东结合起来, 那么结合的方式是?
> 1.使用 http 或者 RPC 方式.塞入任务,并消费队列?
> 2.其他框架只负责往 redis 塞入任务,这个东东自动去消费队列?
> 3.其他好的建议是?

了解。建议 1，主要原因是往队列塞的东西需要是序列化后的类，这个类的定义应该是在消费者可以读取到的。

**Comment by jonny77** [comment]
> > > 你好，谢谢反馈。接入其他框架，只需要保证任务类中的执行代码（可能引用了外部类）支持 composer 加载就可以了，如果不支持那需要手动引入需要的代码。
> > > 
> > > 1. 是建议还是？
> > > 2. 是的。保证生产者和消费者都在同一个项目即可。
> > > 3. 在我司已经生产验证，每天消费百万消息。
> > 
> > 
> > 其实我就想问有什么方式可以将别的框架跟你这个东东结合起来, 那么结合的方式是?
> > 1.使用 http 或者 RPC 方式.塞入任务,并消费队列?
> > 2.其他框架只负责往 redis 塞入任务,这个东东自动去消费队列?
> > 3.其他好的建议是?
> 
> 了解。建议 1，主要原因是往队列塞的东西需要是序列化后的类，这个类的定义应该是在消费者可以读取到的。

OK ,你的意思是建议使用这个东东塞入任务咯

**Comment by Littlesqx** [comment]
对的

**Comment by jonny77** [comment]
<img width="922" alt="WX20200522-102303@2x" src="https://user-images.githubusercontent.com/1962170/82624887-522b3b80-9c16-11ea-8aaf-d42540dd4b0e.png">
出现了这个问题是怎么回事. 是我环境的问题吗 ? mac  最新系统. php7.2.26

**Comment by Littlesqx** [comment]
> <img alt="WX20200522-102303@2x" width="922" src="https://user-images.githubusercontent.com/1962170/82624887-522b3b80-9c16-11ea-8aaf-d42540dd4b0e.png">
> 
> 出现了这个问题是怎么回事. 是我环境的问题吗 ? mac 最新系统. php7.2.26

看不出来，应该是 PHP 或者某个扩展没装好。

**Comment by jonny77** [comment]
> > <img alt="WX20200522-102303@2x" width="922" src="https://user-images.githubusercontent.com/1962170/82624887-522b3b80-9c16-11ea-8aaf-d42540dd4b0e.png">
> > 出现了这个问题是怎么回事. 是我环境的问题吗 ? mac 最新系统. php7.2.26
> 
> 看不出来，应该是 PHP 或者某个扩展没装好。

![WX20200523-153628](https://user-images.githubusercontent.com/1962170/82724796-43728080-9d0b-11ea-8f32-7a6e26884be5.png)
YII2 框架安装的时候报错了

**Comment by Littlesqx** [comment]
意思是包冲突了，检查看看有没有其他包也用了 symfony/console，版本要统一一下，你帮我查一下，我看下能不能我这边升级

**Comment by Littlesqx** [comment]
我更新了，晚些时候试一下重新安装，应该没问题了。https://github.com/Littlesqx/aint-queue/releases/tag/v1.2.0

**Comment by Littlesqx** [comment]
@jonny77 https://github.com/Littlesqx/aint-queue/tree/master/example/yii2-project 我加上了一个例子，里面有通过 Factory 获取队列，也有注册全局的组件，生产者在 QueueController，启动消费者还是和文档的一样。
