### ISSUE TITLE
可以弄一个如何 投递任务和处理任务的 demo 吗?

### ISSUE THREAD

**Issue by jonny77** [Littlesqx/aint-queue#30]
RT

**Comment by Littlesqx** [comment]
看看这里的例子 https://github.com/Littlesqx/aint-queue/tree/master/example/project 满足你的需求没有，有投递任务（curl -v http://localhost:8000
）和处理任务（./vendor/bin/aint-queue worker:listen --channel=example
）

**Comment by jonny77** [comment]
curl -v http://localhost:8000 普通http投递一个任务貌似要100多毫秒  是你框架的问题还是???
