### ISSUE TITLE
命令行启动任务监听的时候如何指定我自定义的config文件

### ISSUE THREAD

**Issue by jonny77** [Littlesqx/aint-queue#31]

**Comment by Littlesqx** [comment]
默认读取配置路径： config/aint-queue.php

可以参考 example 目录的例子

**Comment by jonny77** [comment]
> 默认读取配置路径： config/aint-queue.php
> 
> 可以参考 example 目录的例子

感觉你这东东是独立运行使用的. 跟其他框架结合貌似不太友好. 看了你的 demo 貌似是通过 curl 投递的任务

**Comment by Littlesqx** [comment]
> > 默认读取配置路径： config/aint-queue.php
> > 可以参考 example 目录的例子
> 
> 感觉你这东东是独立运行使用的. 跟其他框架结合貌似不太友好. 看了你的 demo 貌似是通过 curl 投递的任务

其他框架一样的，我有空写个 yii2 和 laravel 的 demo 给你，投递任务 curl 只是为了演示，具体什么时候在哪里触发都是你决定的。

**Comment by jonny77** [comment]
> > > 默认读取配置路径： config/aint-queue.php
> > > 可以参考 example 目录的例子
> > 
> > 
> > 感觉你这东东是独立运行使用的. 跟其他框架结合貌似不太友好. 看了你的 demo 貌似是通过 curl 投递的任务
> 
> 其他框架一样的，我有空写个 yii2 和 laravel 的 demo 给你，投递任务 curl 只是为了演示，具体什么时候在哪里触发都是你决定的。

好的，多谢
