### ISSUE TITLE
感觉要放弃了

### ISSUE THREAD

**Issue by jonny77** [Littlesqx/aint-queue#32]
Fatal error: Uncaught TypeError: Return value of "Littlesqx\AintQueue\Console\Command\WorkerListenCommand::execute()" must be of the type int, "NULL" returned. in /Users/xxx/Documents/www/queue/vendor/symfony/console/Command/Command.php:258

**Comment by jonny77** [comment]
vendor/bin/aint-queue worker:listen --channel=example
执行命令的时候报错的

**Comment by Littlesqx** [comment]
不好意思，升级 symfony/console 后有了新 bug，试一下升级到 1.2.1

https://github.com/Littlesqx/aint-queue/releases/tag/v1.2.1
