### ISSUE TITLE
[Error] The config of queue "default" is not provided.

### ISSUE THREAD

**Issue by shuipf** [Littlesqx/aint-queue#34]
刚看到安装了下，运行 bin/aint-queue queue:dashboard
提示这个错误~~
我有创建config/aint-queue.php 文件

**Comment by shuipf** [comment]
好像只能-t example加这个参数能运行起来，aint-queue.php 配置文件貌似不管用

**Comment by shuipf** [comment]
估计一直使用的是默认配置 /vendor/littlesqx/aint-queue/src/Config/config.php

**Comment by Littlesqx** [comment]
@shuipf 请提供创建的 aint-queue.php 文件。-t 参数是指定 channel（如果没有加参数，默认认为是 `default`），我猜你的文件只有 `example` 配置，没有 `default` 配置

**Comment by shuipf** [comment]
我配置文件你有改成default的
![image](https://user-images.githubusercontent.com/2285144/88138346-1154a080-cc20-11ea-890e-b919840e337a.png)

我就怀疑没走我这个配置文件

**Comment by Littlesqx** [comment]
你是怎么安装的，直接 clone 还是 composer？可以看看你的项目路径吗，建议可以参考下 example 的例子

**Comment by shuipf** [comment]
我第一次用你说明文档的方式，安装的不行，最后我就用clone方式下来，再执行安装也是不行~~~所以我就奇怪了
![image](https://user-images.githubusercontent.com/2285144/88140646-af4a6a00-cc24-11ea-84fa-d6926e5a70ff.png)
app、config、public都是从里example日志出来的。

**Comment by shuipf** [comment]
有QQ或者微信吗？想和作者交个朋友，感觉挺佩服的~

**Comment by Littlesqx** [comment]
@shuipf 微信 littletsian_wx 备注来源

**Comment by Littlesqx** [comment]
> 我第一次用你说明文档的方式，安装的不行，最后我就用clone方式下来，再执行安装也是不行~~~所以我就奇怪了
> ![image](https://user-images.githubusercontent.com/2285144/88140646-af4a6a00-cc24-11ea-84fa-d6926e5a70ff.png)
> app、config、public都是从里example日志出来的。

安装有误，请参考 example 例子
