### ISSUE TITLE
yii2高级模板 使用的时候 消费队列报错

### ISSUE THREAD

**Issue by assassin0905** [Littlesqx/aint-queue#40]
Fatal error: Littlesqx\AintQueue\Worker\ConsumerWorker::handle(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "api\jobs\SimpleJob" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in var/project/vendor/littlesqx/aint-queue/src/Worker/ConsumerWorker.php on line 124

**Comment by Littlesqx** [comment]
你好谢谢反馈，提示说找不到对应的反序列化的类，方法：请确保消费者能访问的生产者序列化的类，建议都是统一加载规则，如 PSR4
